export const appsData = [
  {
    id: "daily-learning",
    category: "Aprendizaje",
    title: "Micro-lecciones diarias",
    problem: "Aprender un poco cada dia sin perder continuidad ni saturarte.",
    benefit: "Duplica tu constancia",
    summary: "Una app ligera para avanzar 7 minutos al dia con progreso visible y recordatorios claros.",
    details:
      "Pensada para personas que quieren aprender de forma constante sin abrir una plataforma pesada ni navegar menus complejos.",
    steps: [
      "Elige un tema o ruta de aprendizaje.",
      "Completa una micro-leccion de 5 a 7 minutos.",
      "Marca el avance y recibe el siguiente paso.",
    ],
    value: "Mantiene el ritmo con una experiencia simple y medible.",
    stack: ["React", "Node", "SQLite"],
    tags: ["Aprendizaje", "Habitos"],
    theme: "red",
    preview: {
      type: "learning",
      metric: "07 min",
      lesson: "Leccion del dia",
      progress: 68,
      checklist: ["Repaso rapido", "Nueva idea", "Mini quiz"],
    },
  },
  {
    id: "smart-cooking",
    category: "Hogar",
    title: "Cocina sin errores",
    problem: "Seguir recetas largas sin perder tiempos ni pasos importantes.",
    benefit: "Evita errores al cocinar",
    summary: "Timers inteligentes y pasos simples para cocinar con control y menos improvisacion.",
    details:
      "Ideal para cocinar con mas seguridad, menos distracciones y una guia visual que no te hace perder el hilo.",
    steps: [
      "Abre la receta y mira el primer paso.",
      "Activa timers y alertas en el momento correcto.",
      "Marca cada paso para no repetir ni saltarte nada.",
    ],
    value: "Cocinas con mas calma y menos margen para equivocarte.",
    stack: ["Flutter", "Firebase", "APIs"],
    tags: ["Hogar", "Utilidad"],
    theme: "yellow",
    preview: {
      type: "cooking",
      timer: "12:00",
      heat: "180 C",
      checklist: ["Preparar", "Cocinar", "Servir"],
    },
  },
  {
    id: "focus-session",
    category: "Productividad",
    title: "Sesion de foco",
    problem: "Estudiar o trabajar sin caer en distracciones constantes.",
    benefit: "Duplica tu foco",
    summary: "Bloquea ruido digital, organiza sesiones cortas y mantiene el pulso de avance.",
    details:
      "Sirve para estudiar, escribir o trabajar en bloques cortos con una pantalla que prioriza lo esencial.",
    steps: [
      "Arranca una sesion de trabajo con un solo objetivo.",
      "Bloquea distracciones y deja visibles solo lo importante.",
      "Cierra la sesion con un resumen del avance logrado.",
    ],
    value: "Te ayuda a entrar en ritmo y mantener la atencion por mas tiempo.",
    stack: ["React", "Python", "Webhooks"],
    tags: ["Productividad", "Estudio"],
    theme: "pink",
    preview: {
      type: "focus",
      timer: "45:00",
      blocked: 4,
      progress: 72,
      distractions: ["Reels", "Mail", "Tabs"],
    },
  },
  {
    id: "task-tray",
    category: "Organizacion",
    title: "Tareas sin friccion",
    problem: "Las ideas se quedan sueltas y se vuelven procrastinacion.",
    benefit: "Reduce el desorden mental",
    summary: "Convierte pendientes simples en una lista accionable y facil de completar.",
    details:
      "Para capturar pendientes rapidos, ordenarlos por prioridad y ver el siguiente paso sin pensar demasiado.",
    steps: [
      "Captura la tarea en un inbox rapido.",
      "Llevate solo lo que importa al plan de hoy.",
      "Marca lo hecho y vacia la mente de ruido.",
    ],
    value: "Menos decisiones, mas accion inmediata.",
    stack: ["Vue", "Node", "LocalStorage"],
    tags: ["Organizacion", "Trabajo"],
    theme: "white",
    preview: {
      type: "tasks",
      columns: [
        {
          label: "Inbox",
          items: ["Pagar luz", "Nuevo pedido"],
        },
        {
          label: "Hoy",
          items: ["Responder cliente"],
        },
        {
          label: "Hecho",
          items: ["Enviar propuesta", "Cerrar semana"],
        },
      ],
    },
  },
  {
    id: "habit-loop",
    category: "Bienestar",
    title: "Habitos visuales",
    problem: "Mantener rutinas cuando no ves el progreso con claridad.",
    benefit: "Sostiene el habito",
    summary: "Un tablero visual para registrar cadenas, recordatorios y pequenas victorias.",
    details:
      "Diseñada para dar claridad diaria, mostrar constancia y convertir pequenos avances en una senal visible.",
    steps: [
      "Marca el habito que quieres sostener.",
      "Revisa la cadena y la continuidad del dia.",
      "Usa la senal visual para no romper el ritmo.",
    ],
    value: "Convierte la constancia en algo visible y motivador.",
    stack: ["React Native", "Supabase", "Charts"],
    tags: ["Habitos", "Bienestar"],
    theme: "emerald",
    preview: {
      type: "habits",
      streak: "12 dias",
      goal: "Racha activa",
      progress: 74,
      heatmap: [1, 0, 2, 1, 1, 0, 3, 2, 1, 1, 0, 2, 1, 3, 1, 0, 1, 2, 1, 1],
      habits: ["Agua", "Lectura", "Movimiento"],
    },
  },
];
